name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t baris48/multi-containers -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true baris48/multi-containers npm test
 
      - run: docker build -t baris48/multi-containers-client ./client
      - run: docker build -t baris48/multi-containers-nginx ./nginx
      - run: docker build -t baris48/multi-containers-server ./server
      - run: docker build -t baris48/multi-containers-worker ./worker
 
      - run: docker push baris48/multi-containers-client
      - run: docker push baris48/multi-containers-nginx 
      - run: docker push baris48/multi-containers-server 
      - run: docker push baris48/multi-containers-worker 
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multi-containers
          environment_name: Dockermulticontainers-env
          existing_bucket_name: elasticbeanstalk-us-east-1-771619524940
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip